global with sharing class ExceptionHandeler {
    public static void logError(Exception e, String source) {
        /*Exception__c exception = new Exception__c();
        exRecord.Source__c     = source;
        exRecord.Message__c    = exception.getMessage();
        exRecord.StackTrace__c = exception.getStackTraceString();
        exRecord.LineNumber__c   = exception.getLineNumber();
        insert exception;*/
        
    }
}